# render.yaml

services:
  - type: web
    name: live-stock-predictor
    runtime: python
    plan: free # or "starter"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4 # Prophet works well with recent Python versions
